/*
 * FROZEN CONTRACT. Owned by the orchestrator session.
 * Codex-1, Codex-2 and the MiniMax session all build against these types.
 * Do not edit this file. If a change is truly needed, write the request in
 * handoffs/STATUS.md and stop touching code that depends on the change.
 */

export type EventFlag =
  | "surgery"
  | "emergency"
  | "imaging"
  | "first-visit"
  | "gap-after"
  | "work-status";

export interface CaseEvent {
  /** Stable id derived from row order, e.g. "e-0007". */
  id: string;
  /** Exhibit number, 1-based in chronological order. Undated events number last. */
  exhibit: number;
  /** ISO date "yyyy-mm-dd", or null when the row has no parseable date. */
  date: string | null;
  /** Providers split on ";" and trimmed. Empty array when missing. */
  providers: string[];
  facility: string | null;
  /** Body parts split on "," , trimmed, Title Case, deduplicated. */
  bodyParts: string[];
  /** Trimmed medicine type. Null when missing; UI shows "Unclassified". */
  medicineType: string | null;
  recordType: string | null;
  /** Raw summary text from the Excel. Empty string when missing. */
  summary: string;
  /** Hyperlink target of the "Link To Pdf" cell, if any. */
  pdfUrl: string | null;
  /** Derived via SEVERITY_RULES below. */
  severity: 1 | 2 | 3 | 4;
  flags: EventFlag[];
  /** Deterministic short label: "<Record type> - <top body part> (<provider>)". */
  headline: string;
  /** Optional AI-written headline. UI prefers this when present. */
  aiHeadline?: string;
  /** Id of the phase this event belongs to. */
  phaseId?: string;
  /** Original row values keyed by the original header text. */
  raw: Record<string, string>;
}

export interface CaseMilestone {
  id: string;
  date: string; // ISO
  label: string;
  kind: "accident" | "custom";
}

export type PhaseKind =
  | "emergency"
  | "diagnostics"
  | "surgery"
  | "therapy"
  | "recovery"
  | "other";

export interface CasePhase {
  id: string;
  label: string;
  kind: PhaseKind;
  start: string; // ISO
  end: string; // ISO
  eventIds: string[];
}

export interface CaseStats {
  totalEvents: number;
  firstDate: string | null;
  lastDate: string | null;
  dateSpanDays: number;
  providerCount: number;
  facilityCount: number;
  byMedicineType: Record<string, number>;
  byBodyPart: Record<string, number>;
  byRecordType: Record<string, number>;
  /** "yyyy-mm" buckets covering the whole span, zero-filled. */
  visitsPerMonth: { month: string; count: number; severitySum: number }[];
}

export interface ImportReport {
  rowsRead: number;
  eventsLoaded: number;
  missingDates: number;
  missingProviders: number;
  missingBodyParts: number;
  missingMedicineType: number;
  /** Canonical field -> original header text that was matched. */
  headerMap: Record<string, string>;
  warnings: string[];
}

export interface CaseModel {
  id: string;
  /** Display name, from the file name, e.g. "Caldwell". */
  name: string;
  sourceFileName: string;
  importedAt: string; // ISO datetime
  /** Sorted by date ascending. Undated events are LAST, in row order. */
  events: CaseEvent[];
  undatedCount: number;
  milestones: CaseMilestone[];
  phases: CasePhase[];
  stats: CaseStats;
  importReport: ImportReport;
  aiCaseSummary?: string;
}

/*
 * Shared derivation rules. The parser applies them; every other module may
 * rely on them (hover explanations, story mode, exports).
 * Matching input is "<Record Type> <Medicine Type>" lowercased.
 * First rule that matches wins. Default severity is 2.
 */
export const SEVERITY_RULES: { level: 1 | 2 | 3 | 4; pattern: RegExp; reason: string }[] = [
  { level: 4, pattern: /operat|surger|surgic|anesthes/i, reason: "Surgical or operative care" },
  { level: 3, pattern: /emergen|\bems\b|ambulance|admiss|inject|procedure|hospital/i, reason: "Emergency or invasive care" },
  { level: 1, pattern: /admin|billing|form|order|education|reimburse|misc|letter|correspond/i, reason: "Administrative record" },
];

export const FLAG_RULES: { flag: EventFlag; pattern: RegExp }[] = [
  { flag: "surgery", pattern: /operat|surger|surgic/i },
  { flag: "emergency", pattern: /emergen|\bems\b|ambulance/i },
  { flag: "imaging", pattern: /imaging|\bmri\b|\bct\b|x-?ray|radiol|ultrasound/i },
  { flag: "work-status", pattern: /work (ability|status|condition)|disability|restriction/i },
];

/** A gap-after flag is set when the next dated event is more than this many days away. */
export const GAP_DAYS = 45;
